In [1]:
import pandas as pd

In [12]:
hist_data = pd.read_csv("hydro_hist.csv")

In [26]:
prefix_to_match = "NE"
NE_hist_data = hist_data[hist_data["PU_CODE"].str.startswith(prefix_to_match)]
NE_hist_data

,OBJECTID,COMID,GNIS_NAME,LENGTHKM,FTYPE,PU_CODE,TOTDASQKM,TIDAL,WBAREATYPE,MA_HIST,...,HIQ1_5_HIST,HIQ10_HIST,HIQ25_HIST,LO7Q1_HIST,LO7Q10_HIST,BFI_HIST,LO7Q1DT_HIST,CFM_HIST,W95_HIST,SHAPE_Length
1893467,1893468,2680086,Tunk Stream,0.597,460,NE01,59.4171,0,NaN,42.452978,...,209.069529,606.007619,765.228374,7.811320,6.455424,0.191850,232.014286,157.854789,7.565517,0.007099
1893468,1893469,2680084,Tunk Stream,1.042,460,NE01,50.5503,0,NaN,36.104634,...,178.001735,514.427735,650.078048,6.636746,5.486008,0.191666,232.014286,157.852329,7.565517,0.012082
1893469,1893470,2677318,Whitten Parritt Stream,1.420,460,NE01,23.2200,0,NaN,16.431149,...,80.683228,227.023749,289.203544,2.974254,2.473510,0.188851,232.342857,157.715181,7.655172,0.014430
1893470,1893471,2691996,Whitten Parritt Stream,0.247,334,NE01,23.3757,0,NaN,16.540562,...,81.219601,228.495439,291.093973,2.993790,2.489836,0.188834,232.342857,157.714570,7.655172,0.002218
1906743,1906744,1721757,Eighteen Pond Brook,1.121,460,NE01,5.0751,0,NaN,2.990598,...,15.989616,30.028418,35.283177,0.680316,0.608248,0.237011,232.685714,169.761236,3.248276,0.013117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2061263,2061264,2676978,Bells Brook,0.669,460,NE01,4.3578,0,NaN,3.261132,...,12.934081,25.732485,35.986291,0.593013,0.513782,0.188191,237.342857,160.169368,7.731034,0.007356
2061264,2061265,2676950,Bells Brook,2.835,460,NE01,1.5300,0,NaN,1.144966,...,4.541086,9.034536,12.634592,0.208204,0.180386,0.188191,237.342857,160.169368,7.731034,0.027585
2061265,2061266,2674052,Allen Stream,3.948,460,NE01,33.6186,0,NaN,21.310961,...,88.222978,171.224540,239.940492,4.910881,4.123211,0.238932,235.814286,165.527634,5.324138,0.038640
2061266,2061267,2679238,Alligator Stream,1.200,460,NE01,194.4477,0,NaN,0.603572,...,3.159069,9.496065,13.048337,0.112270,0.095433,0.192884,229.057143,163.591048,6.834483,0.014393
2061267,2061268,2680674,Alligator Stream,8.722,460,NE01,228.7530,0,NaN,12.604243,...,62.403248,184.948366,267.715029,2.420501,2.030035,0.199089,229.557143,164.820510,5.862069,0.092704

In [27]:
mid_data = pd.read_csv("hydro_mid.csv")
NE_mid_data = mid_data[mid_data["PU_CODE"].str.startswith(prefix_to_match)]
NE_mid_data

,OBJECTID,COMID,GNIS_NAME,LENGTHKM,FTYPE,PU_CODE,TOTDASQKM,TIDAL,WBAREATYPE,MA_2040,...,HIQ1_5_2040,HIQ10_2040,HIQ25_2040,LO7Q1_2040,LO7Q10_2040,BFI_2040,LO7Q1DT_2040,CFM_2040,W95_2040,SHAPE_Length
1875294,1875295,2675360,,1.911,558,NE01,9.8730,0,LakePond,6.672736,...,27.928346,72.850253,84.593160,1.243005,1.033254,0.195049,232.471429,155.311582,12.268966,0.022542
1875295,1875296,2674872,,1.806,460,NE01,2.5479,0,NaN,1.722016,...,7.207397,18.800279,21.830742,0.320779,0.266649,0.195049,232.471429,155.311582,12.268966,0.019188
1921219,1921220,7733097,Greenwich Creek,0.098,460,NE01,19.9062,1,NaN,15.173511,...,62.179114,230.454832,329.338155,3.941001,2.991148,0.269333,240.471429,163.592888,10.427586,0.000882
1921220,1921221,25077348,Greenwich Creek,0.646,558,NE01,19.4958,1,NaN,14.866608,...,60.993245,226.502782,323.801531,3.857038,2.928520,0.269036,240.471429,163.574633,10.406897,0.006189
1921221,1921222,25077346,Greenwich Creek,0.535,558,NE01,18.8055,0,LakePond,14.350391,...,58.998592,219.657336,314.528437,3.715809,2.823178,0.268509,240.471429,163.542165,10.441379,0.004808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2048141,2048142,6125331,Queset Brook,1.177,460,NE01,26.6310,0,NaN,20.638464,...,98.956866,375.393837,504.856333,3.887414,3.069961,0.196243,236.235714,156.327674,12.096552,0.013502
2048142,2048143,6125803,Queset Brook,1.241,558,NE01,24.8229,0,LakePond,19.220328,...,92.266392,345.886675,469.184968,3.609213,2.851980,0.195672,236.235714,156.263526,12.103448,0.013889
2048143,2048144,6125787,Queset Brook,0.012,558,NE01,19.9656,0,NaN,15.410629,...,73.631136,267.090076,373.357015,2.861799,2.266605,0.193616,236.185714,156.032620,12.179310,0.000111
2048144,2048145,6125279,Queset Brook,1.980,460,NE01,22.3974,0,NaN,17.317949,...,82.992097,306.539475,421.333137,3.236016,2.559676,0.194760,236.235714,156.160944,12.137931,0.019028
2048145,2048146,6125785,Queset Brook,0.337,558,NE01,19.9638,0,LakePond,15.409217,...,73.624142,267.060875,373.321503,2.861522,2.266388,0.193615,236.185714,156.032513,12.179310,0.003206

In [28]:
late_data = pd.read_csv("hydro_late.csv")
NE_late_data = late_data[late_data["PU_CODE"].str.startswith(prefix_to_match)]
NE_late_data

,OBJECTID,COMID,GNIS_NAME,LENGTHKM,FTYPE,PU_CODE,TOTDASQKM,TIDAL,WBAREATYPE,MA_2080,...,HIQ1_5_2080,HIQ10_2080,HIQ25_2080,LO7Q1_2080,LO7Q10_2080,BFI_2080,LO7Q1DT_2080,CFM_2080,W95_2080,SHAPE_Length
1850560,1850561,6712013,,0.558,460,NE01,384.8499,0,NaN,0.335655,...,1.627272,5.137046,6.076963,0.053933,0.044800,0.169572,243.350000,150.087146,12.544828,0.005601
1850561,1850562,6712041,,1.025,460,NE01,122.9562,0,NaN,95.235396,...,477.819151,1447.263621,1792.857938,15.557394,12.720133,0.172218,244.128571,150.584640,12.572414,0.010673
1850562,1850563,6712145,Potash Brook,3.965,460,NE01,6.5880,0,NaN,5.315690,...,26.282642,87.574796,123.780377,0.876955,0.711265,0.173555,243.350000,151.263705,12.393103,0.039407
1850922,1850923,6711985,Dead River,4.771,460,NE01,25.9038,0,NaN,20.502517,...,103.219095,413.991887,539.240152,3.216666,2.684274,0.164994,242.514286,151.628901,12.027586,0.050909
1850923,1850924,6711997,Webber Brook,5.933,460,NE01,7.3764,0,NaN,5.557627,...,26.943673,85.057035,100.619782,0.892997,0.741775,0.169572,243.350000,150.087146,12.544828,0.064061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2165550,2165551,9315803,,2.318,460,NE01,2.1582,0,NaN,1.648803,...,7.645363,19.727415,27.337665,0.233822,0.197094,0.149587,238.771429,148.219008,13.717241,0.024765
2165551,2165552,9315815,,1.608,460,NE01,2.7765,0,NaN,2.121167,...,9.835672,25.379093,35.169594,0.300809,0.253559,0.149587,238.771429,148.219007,13.717241,0.019898
2165552,2165553,9315891,Moulton Brook,2.312,460,NE01,1.9215,0,NaN,1.467971,...,6.806859,17.563813,24.339411,0.208178,0.175478,0.149587,238.771429,148.219007,13.717241,0.025018
2165553,2165554,9315937,Bennett Brook,3.689,460,NE01,4.8159,0,NaN,3.670264,...,17.003242,44.008355,61.510967,0.521294,0.439857,0.150213,239.185714,148.265651,13.703448,0.038220
2165554,2165555,9312941,,1.389,460,NE01,5.3046,0,NaN,3.958602,...,19.320836,56.560075,72.441370,0.566072,0.476016,0.151363,241.485714,148.673613,13.393103,0.013617

In [29]:
mid_abs_change = pd.read_csv("abs_change_mid.csv")
NE_mid_abs_change = mid_abs_change[mid_abs_change["PU_CODE"].str.startswith(prefix_to_match)]
NE_mid_abs_change

,OBJECTID,COMID,GNIS_NAME,LENGTHKM,FTYPE,PU_CODE,TOTDASQKM,TIDAL,WBAREATYPE,MA_A2040,...,HIQ1_5_A2040,HIQ10_A2040,HIQ25_A2040,LO7Q1_A2040,LO7Q10_A2040,BFI_A2040,LO7Q1DT_A2040,CFM_A2040,W95_A2040,SHAPE_Length
1703377,1703378,7690385,Coys Brook,2.622,460,NE01,1.7154,0,NaN,0.049288,...,0.003118,-0.158677,-2.484399,-0.004807,-0.001372,-0.011906,4.571429,-1.799128,2.041379,0.025947
1703378,1703379,7691657,Dunn Brook,1.030,460,NE01,18.3402,0,NaN,0.557979,...,-0.958977,14.706915,30.831441,-0.043183,-0.013566,-0.011353,4.014286,-1.426153,2.144828,0.010134
1703379,1703380,7692073,Dunn Brook,0.118,558,NE01,18.3744,0,StreamRiver,0.559044,...,-0.958690,14.763894,30.906921,-0.043260,-0.013550,-0.011353,4.014286,-1.425866,2.144828,0.001387
1703380,1703381,7690517,Dunn Brook,0.316,460,NE01,15.6006,0,NaN,0.472649,...,-0.648073,10.120179,24.870366,-0.037103,-0.014836,-0.011388,3.178571,-1.453298,2.137931,0.002981
1703381,1703382,7691627,Dunn Brook,1.889,460,NE01,14.2704,0,NaN,0.431218,...,-0.465153,7.906082,21.468707,-0.034182,-0.015086,-0.011413,3.150000,-1.470304,2.117241,0.018062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2190967,2190968,1720983,Big Wilson Stream,0.320,460,NE01,125.2665,0,NaN,7.663541,...,26.665402,58.595741,-9.171424,-0.641424,-0.143831,-0.026577,5.271429,-10.982658,4.310345,0.003900
2190968,2190969,1720985,Big Wilson Stream,2.141,460,NE01,113.1723,0,NaN,6.885723,...,26.205304,52.184857,-21.267365,-0.583313,-0.128171,-0.026245,5.664286,-11.072382,4.282759,0.024626
2190969,2190970,1720953,Big Wilson Stream,0.506,460,NE01,106.3530,0,NaN,6.447151,...,26.386683,48.570088,-28.087647,-0.535989,-0.104556,-0.025904,12.457143,-11.131868,4.241379,0.005403
2190970,2190971,1720933,Big Wilson Stream,2.088,460,NE01,104.3613,0,NaN,6.319058,...,26.418255,47.514329,-30.079633,-0.525775,-0.105927,-0.025552,11.528571,-11.150692,4.227586,0.019847
2190971,2190972,1722831,Leeman Brook,3.995,460,NE01,18.6174,0,NaN,1.094618,...,-6.427857,-8.306234,-7.472694,-0.075441,-0.061142,-0.027066,0.492857,-11.051134,6.551724,0.046459

In [30]:
late_abs_change = pd.read_csv("abs_change_late.csv")
NE_late_abs_change = late_abs_change[late_abs_change["PU_CODE"].str.startswith(prefix_to_match)]
NE_late_abs_change

,OBJECTID,COMID,GNIS_NAME,LENGTHKM,FTYPE,PU_CODE,TOTDASQKM,TIDAL,WBAREATYPE,MA_A2080,...,HIQ1_5_A2080,HIQ10_A2080,HIQ25_A2080,LO7Q1_A2080,LO7Q10_A2080,BFI_A2080,LO7Q1DT_A2080,CFM_A2080,W95_A2080,SHAPE_Length
1907742,1907743,6740528,Turee Brook,1.463,460,NE01,8.7885,0,NaN,0.733996,...,4.339213,25.037273,23.321723,-0.043268,-0.041268,-0.045249,9.764286,-4.401240,2.972414,0.016838
1907743,1907744,6740584,,2.882,460,NE01,2.4777,0,NaN,0.206932,...,1.223334,7.058639,6.574983,-0.012198,-0.011634,-0.045249,9.764286,-4.401240,2.972414,0.029463
1907744,1907745,6741450,White Brook,1.729,460,NE01,12.1275,0,NaN,1.005623,...,6.120296,32.110723,32.677128,-0.061808,-0.058014,-0.044134,10.550000,-4.660748,3.020690,0.016901
1907745,1907746,6740554,,2.337,460,NE01,2.5398,0,NaN,0.212118,...,1.253995,7.235554,6.739775,-0.012504,-0.011926,-0.045249,9.764286,-4.401240,2.972414,0.026651
1907746,1907747,6090207,,2.916,460,NE01,10.7802,0,NaN,0.909575,...,0.900336,-3.064542,3.621275,-0.082699,-0.105418,-0.044780,15.142857,-11.061597,4.710345,0.032243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2047424,2047425,5849494,,1.524,558,NE01,282.5181,1,StreamRiver,22.649733,...,123.399951,387.161495,20.662637,-1.642745,-1.273546,-0.031919,8.478571,-4.322353,2.386207,0.016545
2047425,2047426,5849250,,0.929,460,NE01,275.7294,0,NaN,22.083238,...,120.500536,395.496379,16.558252,-1.607638,-1.245106,-0.031944,8.342857,-4.332619,2.379310,0.009208
2047426,2047427,6763298,North Branch River,0.844,460,NE01,24.0489,0,NaN,2.080500,...,0.547533,15.177477,34.446866,-0.177354,-0.205887,-0.032463,7.021429,-11.205994,5.379310,0.008140
2047427,2047428,6763334,Bailey Brook,0.231,460,NE01,18.2754,0,NaN,1.581329,...,0.434129,11.727843,26.387176,-0.134847,-0.156580,-0.032475,7.092857,-11.198834,5.358621,0.002294
2047428,2047429,6763340,Bailey Brook,0.313,460,NE01,15.8382,0,NaN,1.370612,...,0.395723,10.279465,22.951236,-0.116903,-0.135766,-0.032483,7.092857,-11.194246,5.337931,0.003333

In [31]:
mid_prc_change = pd.read_csv("mid_prc_change.csv")
NE_mid_prc_change = mid_prc_change[mid_prc_change["PU_CODE"].str.startswith(prefix_to_match)]
NE_mid_prc_change

,OBJECTID,COMID,GNIS_NAME,LENGTHKM,FTYPE,PU_CODE,TOTDASQKM,TIDAL,WBAREATYPE,MA_P2040,...,MJJA_P2040,MSON_P2040,HIQ1_5_P2040,HIQ10_P2040,HIQ25_P2040,LO7Q1_P2040,LO7Q10_P2040,BFI_P2040,W95_P2040,SHAPE_Length
1928171,1928172,804611,South Branch Machias River,3.650,460,NE01,63.1161,0,NaN,9.278181,...,-4.499426,-1.574410,4.217972,2.391599,-1.217555,-3.543671,-1.073115,-11.065838,402.325581,0.041444
1928172,1928173,804617,South Branch Machias River,4.500,460,NE01,30.2139,0,NaN,9.233735,...,-4.559656,-1.613859,4.542719,1.950736,-0.072451,-3.601168,-1.220555,-11.090146,411.811024,0.049499
1928173,1928174,804633,South Branch Machias River,5.134,460,NE01,19.0008,0,NaN,9.146557,...,-4.711297,-1.690824,5.425691,1.263796,1.987154,-3.714756,-1.299008,-11.060763,423.770492,0.058508
1928174,1928175,805315,Aroostook River,1.615,558,NE01,2604.7791,0,StreamRiver,9.389100,...,-2.423921,-1.569019,0.082857,6.110162,-8.199419,-2.249780,-1.290286,-10.219787,333.684211,0.016191
1928175,1928176,811533,Aroostook River,0.848,558,NE01,2599.9704,0,StreamRiver,9.387815,...,-2.428138,-1.570263,0.087278,6.108058,-8.213101,-2.249800,-1.288733,-10.219146,333.684211,0.008811
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2027432,2027433,9343905,Millers River,0.016,558,NE01,963.5724,0,NaN,6.006625,...,2.097091,-9.326164,1.600870,-9.132425,-17.578799,-2.115497,0.020737,-6.217855,27.715877,0.000189
2027433,2027434,9343473,Millers River,1.326,460,NE01,959.4297,0,NaN,6.010171,...,2.093686,-9.316813,1.612906,-9.258092,-17.601279,-2.117299,0.002408,-6.223004,27.963738,0.014890
2027434,2027435,9343495,Millers River,0.663,460,NE01,955.0242,0,NaN,6.013970,...,2.090035,-9.306787,1.625926,-9.394469,-17.625179,-2.119315,-0.017240,-6.228556,27.944251,0.007237
2027435,2027436,7716636,Beacon Hill Brook,1.097,460,NE01,13.6746,0,NaN,3.609717,...,2.336088,-11.561424,4.957971,3.871286,1.253700,-1.479977,-2.878592,-4.165031,13.946015,0.013054
2027436,2027437,7714882,,0.179,460,NE01,0.0099,0,NaN,3.609281,...,2.202813,-11.707262,7.300272,9.531248,-0.447828,-1.523130,-2.726163,-4.182464,14.664083,0.001958

In [32]:
late_prc_change = pd.read_csv("late_prc_change.csv")
NE_late_prc_change = late_prc_change[late_prc_change["PU_CODE"].str.startswith(prefix_to_match)]
NE_late_prc_change

,OBJECTID,COMID,GNIS_NAME,LENGTHKM,FTYPE,PU_CODE,TOTDASQKM,TIDAL,WBAREATYPE,MA_P2080,...,MJJA_P2080,MSON_P2080,HIQ1_5_P2080,HIQ10_P2080,HIQ25_P2080,LO7Q1_P2080,LO7Q10_P2080,BFI_P2080,W95_P2080,SHAPE_Length
1531614,1531615,803635,West Branch Salmon Brook,1.657,460,NE01,21.8133,0,NaN,16.281889,...,-4.102639,8.969971,-11.346896,34.055591,32.826605,-3.211797,-3.924010,-16.703628,590.277778,0.018378
1531615,1531616,804813,West Branch Salmon Brook,5.195,460,NE01,6.5781,0,NaN,15.972791,...,-4.472007,9.270082,-10.937987,39.693177,36.035131,-3.176600,-3.839287,-16.380923,649.246231,0.061426
1531616,1531617,803663,,3.704,460,NE01,4.2606,0,NaN,22.304111,...,-2.776098,7.224405,3.312906,0.819533,-15.825050,-6.098793,-3.709501,-23.434369,331.876607,0.038425
1708971,1708972,804815,,2.849,460,NE01,3.4146,0,NaN,16.013332,...,-4.507553,9.290899,-10.391853,40.272570,36.609179,-3.433947,-3.774324,-16.427881,665.128205,0.027837
1708972,1708973,803609,,0.357,460,NE01,11.5668,0,NaN,16.564009,...,-3.792908,8.701033,-10.836101,28.461408,22.626932,-3.124119,-4.055938,-16.614853,544.155844,0.003573
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2156355,2156356,7711918,,0.112,460,NE01,61.4610,0,NaN,10.608286,...,-0.030178,-15.583592,12.623017,14.983320,-12.437590,-6.218929,-9.659990,-14.551544,26.289753,0.001056
2156356,2156357,7711922,,0.237,460,NE01,58.6152,0,NaN,10.608286,...,-0.030178,-15.583592,12.623017,14.983320,-12.437590,-6.218929,-9.659990,-14.551544,26.289753,0.002551
2156357,2156358,7711912,,0.667,460,NE01,61.8840,0,NaN,10.608286,...,-0.030178,-15.583592,12.623017,14.983320,-12.437590,-6.218929,-9.659990,-14.551544,26.289753,0.006453
2156358,2156359,7713458,Wangum Lake Brook,2.520,460,NE01,27.7416,0,NaN,10.639766,...,0.022304,-15.591423,12.695265,15.942735,-11.523865,-6.234276,-9.588967,-14.466055,28.396837,0.028648
2156359,2156360,7713460,Wangum Lake Brook,0.443,460,NE01,23.7420,0,NaN,10.645032,...,0.031054,-15.592729,12.905141,16.104928,-11.315133,-6.237149,-9.575188,-14.472958,28.674352,0.004705