# Elastic Net

In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [13]:
data = pd.read_csv('streamdatadf.csv')
data

/var/folders/_z/j1tz7y5s2kq6cgxd5dszn_440000gn/T/ipykernel_26805/1597439229.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('streamdatadf.csv')

          Unnamed: 0  00060_Mean          site_no                   datetime
0                  0       450.0          1010000  1977-01-01 00:00:00+00:00
1                  1       435.0          1010000  1977-01-02 00:00:00+00:00
2                  2       425.0          1010000  1977-01-03 00:00:00+00:00
3                  3       410.0          1010000  1977-01-04 00:00:00+00:00
4                  4       400.0          1010000  1977-01-05 00:00:00+00:00
...              ...         ...              ...                        ...
13560780         270         4.9  411214079465802  1988-10-28 00:00:00+00:00
13560781         271         4.7  411214079465802  1988-10-29 00:00:00+00:00
13560782         272         4.3  411214079465802  1988-10-30 00:00:00+00:00
13560783         273         4.0  411214079465802  1988-10-31 00:00:00+00:00
13560784         274         4.0  411214079465802  1988-11-01 00:00:00+00:00

[13560785 rows x 4 columns]

In [21]:
stream_data = data.drop(columns=['Unnamed: 0']).dropna()
stream_data

          00060_Mean          site_no                   datetime
0              450.0          1010000  1977-01-01 00:00:00+00:00
1              435.0          1010000  1977-01-02 00:00:00+00:00
2              425.0          1010000  1977-01-03 00:00:00+00:00
3              410.0          1010000  1977-01-04 00:00:00+00:00
4              400.0          1010000  1977-01-05 00:00:00+00:00
...              ...              ...                        ...
13560780         4.9  411214079465802  1988-10-28 00:00:00+00:00
13560781         4.7  411214079465802  1988-10-29 00:00:00+00:00
13560782         4.3  411214079465802  1988-10-30 00:00:00+00:00
13560783         4.0  411214079465802  1988-10-31 00:00:00+00:00
13560784         4.0  411214079465802  1988-11-01 00:00:00+00:00

[11842732 rows x 3 columns]

In [22]:
stream_data['year'] = pd.to_datetime(stream_data['datetime']).dt.year
stream_data['month'] = pd.to_datetime(stream_data['datetime']).dt.month
stream_data['day'] = pd.to_datetime(stream_data['datetime']).dt.day

In [23]:
stream_data

,00060_Mean,site_no,datetime,year,month,day
0,450.0,1010000,1977-01-01 00:00:00+00:00,1977,1,1
1,435.0,1010000,1977-01-02 00:00:00+00:00,1977,1,2
2,425.0,1010000,1977-01-03 00:00:00+00:00,1977,1,3
3,410.0,1010000,1977-01-04 00:00:00+00:00,1977,1,4
4,400.0,1010000,1977-01-05 00:00:00+00:00,1977,1,5
...,...,...,...,...,...,...
13560780,4.9,411214079465802,1988-10-28 00:00:00+00:00,1988,10,28
13560781,4.7,411214079465802,1988-10-29 00:00:00+00:00,1988,10,29
13560782,4.3,411214079465802,1988-10-30 00:00:00+00:00,1988,10,30
13560783,4.0,411214079465802,1988-10-31 00:00:00+00:00,1988,10,31
13560784,4.0,411214079465802,1988-11-01 00:00:00+00:00,1988,11,1

In [24]:
X = stream_data.drop(columns=['00060_Mean', 'datetime'])
y = stream_data['00060_Mean']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

elastic_net = ElasticNet(alpha=1.0, l1_ratio=0.5)

elastic_net.fit(X_train, y_train)

y_pred = elastic_net.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

coefficients = elastic_net.coef_
intercept = elastic_net.intercept_
print("Coefficients:", coefficients)
print("Intercept:", intercept)

Mean Squared Error: 178993025.63887578
Coefficients: [ -23.07281727  -39.01909753 -258.58100812    5.49227344]
Intercept: 1754.9074817259723

In [27]:
histdata = pd.read_csv('NE_buffered_1990s.csv')
histdata

,fid,OBJECTID,COMID,GNIS_NAME,LENGTHKM,FTYPE,PU_CODE,TOTDASQKM,TIDAL,WBAREATYPE,...,HIQ1_5_HIST,HIQ10_HIST,HIQ25_HIST,LO7Q1_HIST,LO7Q10_HIST,BFI_HIST,LO7Q1DT_HIST,CFM_HIST,W95_HIST,SHAPE_Length
0,1,456026,3820563,,1.857,460,MS05,1.9746,0,NaN,...,3.333218,7.050051,10.166683,0.206541,0.178316,0.318910,254.342857,172.762614,11.917241,0.019032
1,2,456027,3820719,,1.714,460,MS05,1.4022,0,NaN,...,2.365358,5.007214,7.199864,0.146949,0.126855,0.318873,254.314286,172.826443,11.917241,0.018003
2,3,456028,3824263,,0.088,334,MS05,1.4256,0,NaN,...,2.404527,5.091005,7.314648,0.149476,0.129034,0.318859,254.414286,172.843537,11.917241,0.000977
3,4,456029,3822397,,1.357,460,MS05,5.8842,0,NaN,...,10.416898,22.182167,30.533639,0.629736,0.545379,0.317253,257.228571,173.681304,11.717241,0.013212
4,5,456030,3820721,,0.401,460,MS05,0.8712,0,NaN,...,1.470072,3.110688,4.481323,0.091189,0.078723,0.318904,254.342857,172.784820,11.903448,0.003968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345339,345340,2634814,10449782,,0.627,460,SA03N,12.0375,0,NaN,...,4.889134,10.987235,13.963183,0.473159,0.259122,0.303602,243.807143,174.785331,10.558621,0.005682
345340,345341,2634815,10449826,,0.055,460,SA03N,21944.0898,0,NaN,...,0.454634,1.022164,1.327049,0.038567,0.019883,0.278279,245.328571,173.238838,10.931034,0.000550
345341,345342,2634816,10449830,,0.180,460,SA03N,21944.1105,0,NaN,...,0.483446,1.084209,1.408003,0.041747,0.021697,0.281902,245.057143,173.430991,10.862069,0.001715
345342,345343,2634817,10449836,,0.312,460,SA03N,21944.1465,0,NaN,...,0.533965,1.195626,1.547888,0.047274,0.024866,0.287183,244.864286,173.712382,10.779310,0.003378
345343,345344,2634818,10449838,,0.429,460,SA03N,21944.1510,0,NaN,...,0.056472,0.128983,0.159879,0.006101,0.003463,0.326642,238.950000,176.237554,10.165517,0.004226

In [26]:
merged_data = pd.read_csv('merged_data.csv')
merged_data

/var/folders/_z/j1tz7y5s2kq6cgxd5dszn_440000gn/T/ipykernel_26805/593499213.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  merged_data = pd.read_csv('merged_data.csv')

,Unnamed: 0.1,Unnamed: 0,00060_Mean,site_no,datetime,agency_cd,station_nm
0,0,0,450.0,1010000,1977-01-01 00:00:00+00:00,USGS,"St. John River at Ninemile Bridge, Maine"
1,1,1,435.0,1010000,1977-01-02 00:00:00+00:00,USGS,"St. John River at Ninemile Bridge, Maine"
2,2,2,425.0,1010000,1977-01-03 00:00:00+00:00,USGS,"St. John River at Ninemile Bridge, Maine"
3,3,3,410.0,1010000,1977-01-04 00:00:00+00:00,USGS,"St. John River at Ninemile Bridge, Maine"
4,4,4,400.0,1010000,1977-01-05 00:00:00+00:00,USGS,"St. John River at Ninemile Bridge, Maine"
...,...,...,...,...,...,...,...
13555968,13555968,1420385,134.0,7024000,2006-12-27 00:00:00+00:00,USGS,"BAYOU DE CHIEN NEAR CLINTON, KY"
13555969,13555969,1420386,63.9,7024000,2006-12-28 00:00:00+00:00,USGS,"BAYOU DE CHIEN NEAR CLINTON, KY"
13555970,13555970,1420387,48.4,7024000,2006-12-29 00:00:00+00:00,USGS,"BAYOU DE CHIEN NEAR CLINTON, KY"
13555971,13555971,1420388,45.4,7024000,2006-12-30 00:00:00+00:00,USGS,"BAYOU DE CHIEN NEAR CLINTON, KY"
13555972,13555972,1420389,490.0,7024000,2006-12-31 00:00:00+00:00,USGS,"BAYOU DE CHIEN NEAR CLINTON, KY"

In [29]:
pd.read_csv('PRISM/PRISM_ppt_stable_4kmM2_189501_bil.stn.csv')

                                                     This file contains a list of stations that provided input data to the PRISM run that produced the grid associated with this stn.csv file.
Station Name         Longitude Latitude Elevation(m)                                            Network
047296  REDDING      -122.4000 40.5833  183                                                        COOP
044412  JULIAN       -116.6000 33.0833  1285                                                       COOP
044527  WOFFORD HEIG -118.4500 35.7167  782                                                        COOP
291138  BOSQUE DEL A -106.9000 33.8000  1379                                                       COOP
...                                                                                                 ...
94728   NEW YORK CEN -73.9667  40.7667  30                                                         WBAN
043875  HEALDSBURG   -122.8667 38.6167  31                                                         COOP
94967   PARK RAPIDS  -95.0667  46.9000  440                                                        WBAN
044022  HOLLISTER    -121.4000 36.8500  85                                                         COOP
044288  IOWA HILL    -120.8500 39.0833  906                                                        COOP

[1444 rows x 1 columns]

In [30]:
pd.read_csv('PRISM/PRISM_ppt_stable_4kmM2_198012_bil.stn.csv')

                                                     This file contains a list of stations that provided input data to the PRISM run that produced the grid associated with this stn.csv file.
Station Name         Longitude Latitude Elevation(m)                                            Network
403280  FRANKLIN SEW -86.8667  35.9333  201                                                        COOP
457059  RITZVILLE 1  -118.3667 47.1167  579                                                        COOP
245303  MAC KENZIE   -104.7333 46.1500  857                                                        COOP
044374  JESS VALLEY  -120.3000 41.2667  1617                                                       COOP
...                                                                                                 ...
94918   OMAHA WSFO   -96.0167  41.3667  399                                                        WBAN
94931   HIBBING CHIS -92.8500  47.3833  411                                                        WBAN
94957   FALLS CITY B -95.5833  40.0667  302                                                        WBAN
94967   PARK RAPIDS  -95.0667  46.9000  440                                                        WBAN
044025  HOLLISTER 2  -121.4167 36.8500  84                                                         COOP

[9591 rows x 1 columns]

In [35]:
import requests

# Replace 'YOUR_API_KEY' with your actual NOAA API key
API_KEY = 'DvlSHQkoUvbkbrPkFKZYheKZCFlUFYQe'

# Define the API endpoint to get data
endpoint = "https://www.ncdc.noaa.gov/cdo-web/api/v2/data"

# Specify the parameters for your request, including all desired data types
params = {
    'datasetid': 'GHCND',  # GHCND dataset contains weather data
    'datatypeid': [
        'PRCP',  # Precipitation
        'TMAX',  # Maximum Temperature
        'TMIN',  # Minimum Temperature
        'SNOW',  # Snowfall
        'EVAP',  # Evaporation
        'AWND',  # Average Wind Speed
        'WT16',  # Rain (may include freezing rain, drizzle, and freezing drizzle)
    ],
    'locationid': 'FIPS:23',  # FIPS code for Maine
    'startdate': '1977-01-01',
    'enddate': '1978-01-01',
    'limit': 1000,  # Limit the number of results per request (adjust as needed)
}

# Set up the request headers with your API key
headers = {
    'token': API_KEY
}

# Make the API request
response = requests.get(endpoint, params=params, headers=headers)

if response.status_code == 200:
    data = response.json()
    # Process and extract the data as needed
    for result in data['results']:
        print(result['date'], result['datatype'], result['value'])
else:
    print(f"Request failed with status code {response.status_code}")
    print(response.text)

1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -39
1977-01-01T00:00:00 TMIN -183
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX 17
1977-01-01T00:00:00 TMIN -122
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 TMAX -72
1977-01-01T00:00:00 TMIN -100
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -139
1977-01-01T00:00:00 TMIN -217
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -78
1977-01-01T00:00:00 TMIN -206
1977-01-01T00:00:00 PRCP 13
1977-01-01T00:00:00 SNOW 13
1977-01-01T00:00:00 TMAX -111
1977-01-01T00:00:00 TMIN -222
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -83
1977-01-01T00:00:00 TMIN -228
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -100
1977-01-01T00:00:00 TMIN -206
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -67
1977-01-01T00:00:00 TMIN -222
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -106
1977-01-01T00:00:00 TMIN -178
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 TMAX -94
1977-01-01T00:00:00 TMIN -139
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -78
1977-01-01T00:00:00 TMIN -194
1977-01-01T00:00:00 PRCP 38
1977-01-01T00:00:00 SNOW 25
1977-01-01T00:00:00 PRCP 20
1977-01-01T00:00:00 SNOW 76
1977-01-01T00:00:00 TMAX -156
1977-01-01T00:00:00 TMIN -200
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -11
1977-01-01T00:00:00 TMIN -222
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 TMAX -100
1977-01-01T00:00:00 TMIN -200
1977-01-01T00:00:00 PRCP 3
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 8
1977-01-01T00:00:00 TMAX -106
1977-01-01T00:00:00 TMIN -261
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -111
1977-01-01T00:00:00 TMIN -189
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -117
1977-01-01T00:00:00 TMIN -222
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -83
1977-01-01T00:00:00 TMIN -194
1977-01-01T00:00:00 PRCP 5
1977-01-01T00:00:00 SNOW 8
1977-01-01T00:00:00 TMAX -61
1977-01-01T00:00:00 TMIN -172
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -128
1977-01-01T00:00:00 TMIN -211
1977-01-01T00:00:00 PRCP 3
1977-01-01T00:00:00 SNOW 3
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -94
1977-01-01T00:00:00 TMIN -200
1977-01-01T00:00:00 PRCP 10
1977-01-01T00:00:00 SNOW 18
1977-01-01T00:00:00 TMAX -117
1977-01-01T00:00:00 TMIN -228
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -111
1977-01-01T00:00:00 TMIN -206
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -100
1977-01-01T00:00:00 TMIN -200
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -100
1977-01-01T00:00:00 TMIN -217
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -100
1977-01-01T00:00:00 TMIN -256
1977-01-01T00:00:00 PRCP 8
1977-01-01T00:00:00 SNOW 13
1977-01-01T00:00:00 TMAX -106
1977-01-01T00:00:00 TMIN -211
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -133
1977-01-01T00:00:00 TMIN -228
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -139
1977-01-01T00:00:00 TMIN -250
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -56
1977-01-01T00:00:00 TMIN -189
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 TMAX 6
1977-01-01T00:00:00 TMIN -150
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -89
1977-01-01T00:00:00 TMIN -172
1977-01-01T00:00:00 PRCP 25
1977-01-01T00:00:00 SNOW 25
1977-01-01T00:00:00 TMAX -94
1977-01-01T00:00:00 TMIN -222
1977-01-01T00:00:00 PRCP 18
1977-01-01T00:00:00 SNOW 13
1977-01-01T00:00:00 TMAX -133
1977-01-01T00:00:00 TMIN -217
1977-01-01T00:00:00 PRCP 8
1977-01-01T00:00:00 PRCP 15
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -139
1977-01-01T00:00:00 TMIN -200
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -100
1977-01-01T00:00:00 TMIN -211
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -67
1977-01-01T00:00:00 TMIN -156
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -50
1977-01-01T00:00:00 TMIN -211
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -111
1977-01-01T00:00:00 TMIN -239
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -78
1977-01-01T00:00:00 TMIN -211
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -39
1977-01-01T00:00:00 TMIN -183
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -61
1977-01-01T00:00:00 TMIN -206
1977-01-01T00:00:00 PRCP 5
1977-01-01T00:00:00 SNOW 15
1977-01-01T00:00:00 TMAX -61
1977-01-01T00:00:00 TMIN -211
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -106
1977-01-01T00:00:00 TMIN -217
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -67
1977-01-01T00:00:00 TMIN -178
1977-01-01T00:00:00 PRCP 0
1977-01-01T00:00:00 SNOW 0
1977-01-01T00:00:00 TMAX -44
1977-01-01T00:00:00 TMIN -194
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 0
1977-01-02T00:00:00 TMIN -189
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 6
1977-01-02T00:00:00 TMIN -194
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 TMAX 22
1977-01-02T00:00:00 TMIN -111
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -56
1977-01-02T00:00:00 TMIN -206
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -22
1977-01-02T00:00:00 TMIN -172
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -11
1977-01-02T00:00:00 TMIN -128
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -39
1977-01-02T00:00:00 TMIN -256
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -56
1977-01-02T00:00:00 TMIN -189
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -22
1977-01-02T00:00:00 TMIN -222
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 0
1977-01-02T00:00:00 TMIN -117
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 TMAX 11
1977-01-02T00:00:00 TMIN -122
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -44
1977-01-02T00:00:00 TMIN -189
1977-01-02T00:00:00 PRCP 5
1977-01-02T00:00:00 SNOW 13
1977-01-02T00:00:00 PRCP 8
1977-01-02T00:00:00 SNOW 25
1977-01-02T00:00:00 TMAX -39
1977-01-02T00:00:00 TMIN -172
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 33
1977-01-02T00:00:00 TMIN -156
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 TMAX -50
1977-01-02T00:00:00 TMIN -200
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 PRCP 3
1977-01-02T00:00:00 SNOW 20
1977-01-02T00:00:00 TMAX -44
1977-01-02T00:00:00 TMIN -233
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -11
1977-01-02T00:00:00 TMIN -111
1977-01-02T00:00:00 PRCP 15
1977-01-02T00:00:00 SNOW 25
1977-01-02T00:00:00 TMAX -100
1977-01-02T00:00:00 TMIN -200
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -39
1977-01-02T00:00:00 TMIN -178
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 17
1977-01-02T00:00:00 TMIN -61
1977-01-02T00:00:00 PRCP 3
1977-01-02T00:00:00 SNOW 8
1977-01-02T00:00:00 TMAX -61
1977-01-02T00:00:00 TMIN -200
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -28
1977-01-02T00:00:00 TMIN -233
1977-01-02T00:00:00 PRCP 5
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -67
1977-01-02T00:00:00 TMIN -194
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -44
1977-01-02T00:00:00 TMIN -194
1977-01-02T00:00:00 PRCP 5
1977-01-02T00:00:00 SNOW 13
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 17
1977-01-02T00:00:00 TMIN -122
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -33
1977-01-02T00:00:00 TMIN -100
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -11
1977-01-02T00:00:00 TMIN -144
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -17
1977-01-02T00:00:00 TMIN -122
1977-01-02T00:00:00 PRCP 8
1977-01-02T00:00:00 SNOW 8
1977-01-02T00:00:00 TMAX -72
1977-01-02T00:00:00 TMIN -211
1977-01-02T00:00:00 PRCP 30
1977-01-02T00:00:00 SNOW 76
1977-01-02T00:00:00 TMAX -72
1977-01-02T00:00:00 TMIN -211
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 11
1977-01-02T00:00:00 TMIN -61
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 TMAX 22
1977-01-02T00:00:00 TMIN -144
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 11
1977-01-02T00:00:00 TMIN -128
1977-01-02T00:00:00 PRCP 5
1977-01-02T00:00:00 SNOW 25
1977-01-02T00:00:00 TMAX -44
1977-01-02T00:00:00 TMIN -189
1977-01-02T00:00:00 PRCP 13
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -50
1977-01-02T00:00:00 TMIN -194
1977-01-02T00:00:00 PRCP 5
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -44
1977-01-02T00:00:00 TMIN -139
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 0
1977-01-02T00:00:00 TMIN -228
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 61
1977-01-02T00:00:00 TMIN -128
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 56
1977-01-02T00:00:00 TMIN -72
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -33
1977-01-02T00:00:00 TMIN -206
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -56
1977-01-02T00:00:00 TMIN -200
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 44
1977-01-02T00:00:00 TMIN -50
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -6
1977-01-02T00:00:00 TMIN -72
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -22
1977-01-02T00:00:00 TMIN -111
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX -6
1977-01-02T00:00:00 TMIN -106
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 11
1977-01-02T00:00:00 TMIN -117
1977-01-02T00:00:00 PRCP 0
1977-01-02T00:00:00 SNOW 0
1977-01-02T00:00:00 TMAX 39
1977-01-02T00:00:00 TMIN -128
1977-01-03T00:00:00 PRCP 25
1977-01-03T00:00:00 SNOW 25
1977-01-03T00:00:00 TMAX -17
1977-01-03T00:00:00 TMIN -189
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 6
1977-01-03T00:00:00 TMIN -72
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 TMAX 17
1977-01-03T00:00:00 TMIN -167
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -33
1977-01-03T00:00:00 TMIN -144
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 22
1977-01-03T00:00:00 TMIN -156
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -33
1977-01-03T00:00:00 TMIN -128
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 17
1977-01-03T00:00:00 TMIN -211
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -11
1977-01-03T00:00:00 TMIN -117
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 56
1977-01-03T00:00:00 TMIN -206
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -22
1977-01-03T00:00:00 TMIN -94
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 TMAX 11
1977-01-03T00:00:00 TMIN -161
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 17
1977-01-03T00:00:00 TMIN -139
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -17
1977-01-03T00:00:00 TMIN -183
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 0
1977-01-03T00:00:00 TMIN -183
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 TMAX -6
1977-01-03T00:00:00 TMIN -122
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -6
1977-01-03T00:00:00 TMIN -228
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -44
1977-01-03T00:00:00 TMIN -167
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -39
1977-01-03T00:00:00 TMIN -139
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 0
1977-01-03T00:00:00 TMIN -133
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 6
1977-01-03T00:00:00 TMIN -133
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -39
1977-01-03T00:00:00 TMIN -117
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 33
1977-01-03T00:00:00 TMIN -172
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -33
1977-01-03T00:00:00 TMIN -183
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -6
1977-01-03T00:00:00 TMIN -111
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -6
1977-01-03T00:00:00 TMIN -111
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -33
1977-01-03T00:00:00 TMIN -167
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -50
1977-01-03T00:00:00 TMIN -133
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -44
1977-01-03T00:00:00 TMIN -150
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -33
1977-01-03T00:00:00 TMIN -128
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -22
1977-01-03T00:00:00 TMIN -189
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 22
1977-01-03T00:00:00 TMIN -100
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 TMAX 39
1977-01-03T00:00:00 TMIN -161
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 6
1977-01-03T00:00:00 TMIN -150
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 6
1977-01-03T00:00:00 TMIN -150
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -22
1977-01-03T00:00:00 TMIN -128
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -33
1977-01-03T00:00:00 TMIN -233
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -11
1977-01-03T00:00:00 TMIN -167
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 22
1977-01-03T00:00:00 TMIN -167
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 17
1977-01-03T00:00:00 TMIN -194
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -11
1977-01-03T00:00:00 TMIN -217
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 17
1977-01-03T00:00:00 TMIN -94
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 TMAX 0
1977-01-03T00:00:00 TMIN -344
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -6
1977-01-03T00:00:00 TMIN -111
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -39
1977-01-03T00:00:00 TMIN -144
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -78
1977-01-03T00:00:00 TMIN -183
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -50
1977-01-03T00:00:00 TMIN -211
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX 11
1977-01-03T00:00:00 TMIN -161
1977-01-03T00:00:00 PRCP 0
1977-01-03T00:00:00 SNOW 0
1977-01-03T00:00:00 TMAX -22
1977-01-03T00:00:00 TMIN -156
1977-01-04T00:00:00 PRCP 64
1977-01-04T00:00:00 SNOW 64
1977-01-04T00:00:00 TMAX 28
1977-01-04T00:00:00 TMIN -183
1977-01-04T00:00:00 PRCP 38
1977-01-04T00:00:00 SNOW 25
1977-01-04T00:00:00 TMAX 33
1977-01-04T00:00:00 TMIN -44
1977-01-04T00:00:00 PRCP 13
1977-01-04T00:00:00 TMAX 6
1977-01-04T00:00:00 TMIN -111
1977-01-04T00:00:00 PRCP 41
1977-01-04T00:00:00 PRCP 15
1977-01-04T00:00:00 SNOW 25
1977-01-04T00:00:00 TMAX -33
1977-01-04T00:00:00 TMIN -167
1977-01-04T00:00:00 PRCP 0
1977-01-04T00:00:00 SNOW 0
1977-01-04T00:00:00 TMAX 17
1977-01-04T00:00:00 PRCP 20
1977-01-04T00:00:00 SNOW 33
1977-01-04T00:00:00 TMAX -50
1977-01-04T00:00:00 TMIN -194
1977-01-04T00:00:00 PRCP 28
1977-01-04T00:00:00 SNOW 36
1977-01-04T00:00:00 TMAX 0
1977-01-04T00:00:00 TMIN -189
1977-01-04T00:00:00 PRCP 25
1977-01-04T00:00:00 SNOW 38
1977-01-04T00:00:00 TMAX -17
1977-01-04T00:00:00 TMIN -111
1977-01-04T00:00:00 PRCP 25
1977-01-04T00:00:00 SNOW 25
1977-01-04T00:00:00 TMAX 17
1977-01-04T00:00:00 TMIN -206
1977-01-04T00:00:00 PRCP 41
1977-01-04T00:00:00 SNOW 25
1977-01-04T00:00:00 TMAX 44
1977-01-04T00:00:00 TMIN -72
1977-01-04T00:00:00 PRCP 25
1977-01-04T00:00:00 TMAX 17
1977-01-04T00:00:00 TMIN -111
1977-01-04T00:00:00 PRCP 0
1977-01-04T00:00:00 SNOW 0
1977-01-04T00:00:00 TMAX 6
1977-01-04T00:00:00 TMIN -156
1977-01-04T00:00:00 PRCP 0
1977-01-04T00:00:00 SNOW 0
1977-01-04T00:00:00 PRCP 3
1977-01-04T00:00:00 SNOW 0
1977-01-04T00:00:00 TMAX -72
1977-01-04T00:00:00 TMIN -244
1977-01-04T00:00:00 PRCP 23
1977-01-04T00:00:00 TMAX -17
1977-01-04T00:00:00 TMIN -111
1977-01-04T00:00:00 PRCP 23
1977-01-04T00:00:00 TMAX -33
1977-01-04T00:00:00 TMIN -144
1977-01-04T00:00:00 PRCP 15
1977-01-04T00:00:00 SNOW 8
1977-01-04T00:00:00 PRCP 15
1977-01-04T00:00:00 SNOW 25
1977-01-04T00:00:00 TMAX -22
1977-01-04T00:00:00 TMIN -217
1977-01-04T00:00:00 PRCP 25
1977-01-04T00:00:00 SNOW 51
1977-01-04T00:00:00 TMAX -50
1977-01-04T00:00:00 TMIN -117
1977-01-04T00:00:00 PRCP 20
1977-01-04T00:00:00 SNOW 30
1977-01-04T00:00:00 TMAX -44
1977-01-04T00:00:00 TMIN -144
1977-01-04T00:00:00 PRCP 8
1977-01-04T00:00:00 SNOW 0
1977-01-04T00:00:00 TMAX 0
1977-01-04T00:00:00 TMIN -133
1977-01-04T00:00:00 PRCP 28
1977-01-04T00:00:00 SNOW 33
1977-01-04T00:00:00 TMAX -11
1977-01-04T00:00:00 TMIN -89
1977-01-04T00:00:00 PRCP 18
1977-01-04T00:00:00 SNOW 25
1977-01-04T00:00:00 TMAX -28
1977-01-04T00:00:00 TMIN -117
1977-01-04T00:00:00 PRCP 15
1977-01-04T00:00:00 SNOW 8
1977-01-04T00:00:00 PRCP 33
1977-01-04T00:00:00 SNOW 38
1977-01-04T00:00:00 TMAX 11
1977-01-04T00:00:00 TMIN -167
1977-01-04T00:00:00 PRCP 33
1977-01-04T00:00:00 SNOW 51
1977-01-04T00:00:00 TMAX -28
1977-01-04T00:00:00 TMIN -167
1977-01-04T00:00:00 PRCP 13
1977-01-04T00:00:00 SNOW 25
1977-01-04T00:00:00 TMAX -22
1977-01-04T00:00:00 TMIN -150
1977-01-04T00:00:00 PRCP 10
1977-01-04T00:00:00 SNOW 20
1977-01-04T00:00:00 PRCP 20
1977-01-04T00:00:00 SNOW 38
1977-01-04T00:00:00 TMAX -11
1977-01-04T00:00:00 TMIN -56
1977-01-04T00:00:00 PRCP 61
1977-01-04T00:00:00 SNOW 76
1977-01-04T00:00:00 TMAX -56
1977-01-04T00:00:00 TMIN -122
1977-01-04T00:00:00 PRCP 41
1977-01-04T00:00:00 SNOW 102
1977-01-04T00:00:00 TMAX -61
1977-01-04T00:00:00 TMIN -122
1977-01-04T00:00:00 PRCP 18
1977-01-04T00:00:00 SNOW 51
1977-01-04T00:00:00 TMAX -61
1977-01-04T00:00:00 TMIN -206
1977-01-04T00:00:00 PRCP 33
1977-01-04T00:00:00 SNOW 43
1977-01-04T00:00:00 TMAX -28
1977-01-04T00:00:00 TMIN -144
1977-01-04T00:00:00 PRCP 0

In [38]:
import pandas as pd

# Assuming you have the weather data stored in a list called 'data'
df = pd.DataFrame(data)

# Create a unique key for each entry by combining 'date' and 'datatype'
df['key'] = df['date'] + '_' + df['datatype']

# Pivot the DataFrame using pivot_table and apply a pivot-specific aggregation function
pivot_df = df.pivot_table(index='date', columns='key', values='value', aggfunc='first')

# Reset the index to make the 'date' a column
pivot_df.reset_index(inplace=True)

# Rename the columns to make them more meaningful
column_mapping = {
    '1977-01-01T00:00:00_PRCP': 'Precipitation (mm)',
    '1977-01-01T00:00:00_SNOW': 'Snowfall',
    '1977-01-01T00:00:00_TMAX': 'Max Temperature (°C)',
    '1977-01-01T00:00:00_TMIN': 'Min Temperature (°C)',
    # Add more mappings for other data types...
}
pivot_df.rename(columns=column_mapping, inplace=True)

# Display the resulting DataFrame
print(pivot_df)

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.